name: Jekyll build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: [self-hosted, website]

    steps:
    - name: Checkout current repo to the default location
      uses: actions/checkout@v3
    
    - name: Build the website with jekyll
      uses: jerryjvl/jekyll-build-action@v1
      
    - name: Remove the previous website
      run: rm -r /srv/PINOT-website/_site/* || true
      
    - name: Deploy the new website
      run: mv ./_site/* /srv/PINOT-website/_site/
